### ISSUE TITLE
Explanation of evaluation output

### ISSUE THREAD

**Issue by NNtamp** [LittlePey/SFD#12]
Hello, great work.

I managed to run the evaluation based on your instructions. Could you please explain what every key in output represents in the results.pkl? For example here what are bbox, dimensions, location boxes_lidar etc:

{'name': array(['Car'], dtype='<U3'),
  'truncated': array([0.]),
  'occluded': array([0.]),
  'alpha': array([-7.9565434], dtype=float32),
  'bbox': array([[658.81537, 189.82349, 703.0288 , 223.29366]], dtype=float32),
  'dimensions': array([[4.1351438, 1.411387 , 1.6754185]], dtype=float32),
  'location': array([[ 3.2973313,  2.27376  , 34.605476 ]], dtype=float32),
  'rotation_y': array([-7.8631], dtype=float32),
  'score': array([0.82760674], dtype=float32),
  'boxes_lidar': array([[34.901024 , -3.2707899, -2.0189538,  4.1351438,  1.6754185, 1.411387 ,  6.2923036]], dtype=float32),
  'frame_id': '000002'}

**Comment by LittlePey** [comment]
Hi, we just follow the definition of OpenPCDet code base and we did not investigate each key in detail, but you can refer to this [function](https://github.com/LittlePey/SFD/blob/03f83de462033e4f840f38f0cead44c506b3f1c5/pcdet/datasets/kitti/kitti_dataset.py#L271).  The 'truncated' is the degree of truncation by image boundaries. The 'occluded' is the degree of occlusion by other objects. The 'dimensions' may be [length, height, width], the 'boxes_lidar' may be [x, y, z, length, width, height, rotation].

**Comment by NNtamp** [comment]
Thank you for this.
