### ISSUE TITLE
some error when training(The cloned code did not make any changes)

### ISSUE THREAD

**Issue by Jax29** [LittlePey/SFD#25]
# some error when training:(The cloned code did not make any changes)

- my environment:python3.8,torch1.9.1,cuda11.1,spconv1.2.1;

- single card training:(Report a different error for each training):
1.   questionq1:
![图片](https://user-images.githubusercontent.com/30298452/190348103-9b45c1f7-7cc1-4686-9781-72822bc1f973.png)
2. question2:
![图片](https://user-images.githubusercontent.com/30298452/190350521-40bdc8f7-783a-4ebe-aaa2-d5dbfd9f0441.png)

- Multiple cards training:(Stuck on executing the command)
![图片](https://user-images.githubusercontent.com/30298452/190351148-1cdbedc1-e9ca-449f-aca6-be88e6d8009a.png)
![图片](https://user-images.githubusercontent.com/30298452/190355005-2176b01f-6024-409c-8548-0c559d3047c9.png)

**Comment by goodChiken** [comment]
sorry to distribute u, I also met some issues in the process to realize the code. so can I communicate with u about that. my emial adress is 34054961@qq.com.

**Comment by Dowe-dong** [comment]
Have u solve the first question？ I have met the same one.
