### ISSUE TITLE
KeyError: 'points_pseudo' when try the demo to eval and visualize the result.

### ISSUE THREAD

**Issue by ChunZheng2022** [LittlePey/SFD#28]
(cu113) lcz@wp:~/code/multi_modal/SFD/tools$ python demo.py --cfg_file cfgs/kitti_models/sfd.yaml --ckpt checkpoint_epoch_34.pth --data_path 000001.bin 

Traceback (most recent call last):
  File "demo.py", line 103, in <module>
    main()
  File "demo.py", line 87, in main
    for idx, data_dict in enumerate(demo_dataset):
  File "demo.py", line 52, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/home/lcz/code/multi_modal/SFD/pcdet/datasets/dataset.py", line 143, in prepare_data
    data_dict = self.point_feature_encoder.forward(data_dict)
  File "/home/lcz/code/multi_modal/SFD/pcdet/datasets/processor/point_feature_encoder.py", line 44, in forward
    data_dict['points_pseudo']
KeyError: 'points_pseudo'

**The demo function in OpenPCDet currently does no support reading multimodal input yet.**

**Comment by swaggywilliam** [comment]
I have met the same error, could you tell me how to solve it please? thank you!

**Comment by ChunZheng2022** [comment]
@swaggywilliam Hi, the demo create a demo dataset for inference. And the default demo dataset does not support pseudo points. You can down addition vis tools like this[https://github.com/hailanyi/3D-Detection-Tracking-Viewer](url) to visualize ur results.

**Comment by swaggywilliam** [comment]
> @swaggywilliam Hi, the demo create a demo dataset for inference. And the default demo dataset does not support pseudo points. You can down addition vis tools like this[https://github.com/hailanyi/3D-Detection-Tracking-Viewer](url) to visualize ur results.

您好，请问您的意思是sfd.yaml是使用伪雷达点云数据的，但是OpenPCDet的demo.py并不支持伪雷达点云数据，所以没法用以下命令?
 ```
python demo.py --cfg_file cfgs/kitti_models/sfd.yaml --ckpt checkpoint_epoch_34.pth --data_path 000001.bin
```

**Comment by ChunZheng2022** [comment]
@swaggywilliam 是的，不过你可以使用这个推理脚本或者test.py来得到推理结果，并使用额外的工具进行可视化。
```
scripts/dist_test.sh 8 --cfg_file cfgs/kitti_models/sfd.yaml  --gpu_id 0,1,2,3,4,5,6,7 --batch_size 28 \
--ckpt ../output/kitti_models/sfd/default/ckpt/checkpoint_epoch_40.pth
```
通过这样的方法进行可视化需要添加`--save_to_file`命令。

**Comment by ChunZheng2022** [comment]
可以参考这个 #13  @swaggywilliam

**Comment by swaggywilliam** [comment]
> @swaggywilliam 是的，不过你可以使用这个推理脚本或者test.py来得到推理结果，并使用额外的工具进行可视化。
> 
> ```
> scripts/dist_test.sh 8 --cfg_file cfgs/kitti_models/sfd.yaml  --gpu_id 0,1,2,3,4,5,6,7 --batch_size 28 \
> --ckpt ../output/kitti_models/sfd/default/ckpt/checkpoint_epoch_40.pth
> ```
> 
> 通过这样的方法进行可视化需要添加`--save_to_file`命令。

非常感谢，那我先尝试把train.py跑起来
