### ISSUE TITLE
ONCE数据集生成伪雷达点

### ISSUE THREAD

**Issue by Gmonster-24** [LittlePey/SFD#39]
请问ONCE数据生成伪雷达点只需要原始图像和激光雷达点吗

**Comment by LittlePey** [comment]
您好，您需要先生成ONCE数据集的稠密深度图用以训练深度补全网络，具体而言，你可以使用前后帧的pose信息将前后多帧点云叠加，生成稠密点云，然后将稠密点云投影到图像上生成稠密深度图。您可以先把深度补全网络训练好，这样在训练SFD的时候，您只需要原始图像和单帧的激光雷达点。

**Comment by Gmonster-24** [comment]
非常感谢！
