### ISSUE TITLE
Z-axis deviation invisualization process

### ISSUE THREAD

**Issue by ChunZheng2022** [LittlePey/SFD#42]
Have you ever encountered the problem of Z-axis deviation in the following figure during the visualization process, or do you have any ideas about this problem
![pointvis](https://user-images.githubusercontent.com/54513016/218292426-142e6dfe-f039-4d18-9b4f-614516b588fc.png)

**Comment by ChunZheng2022** [comment]
It turns out that the visualization tool I use is specially made to facilitate observation. Ha ha, let me close this issue

**Comment by HuangLLL123** [comment]
Hello friend, may I ask what tool you use for visualization

**Comment by ChunZheng2022** [comment]
@HuangLLL123 
Hi, HuangLLL123. The vis tool used in the picture is [3d-obj-vis](https://github.com/DeclK/3d-object-vis). It is based on vedo and can directly visualize result.pkl.
And if u want to vis the .txt result, u can try [3D-Detection-Tracking-Viewer](https://github.com/hailanyi/3D-Detection-Tracking-Viewer). Remember to add --save_to_file during validation.
