### ISSUE TITLE
How to evaluate the model in different distence and different occlusion degrees with KITTI?

### ISSUE THREAD

**Issue by Raiden-cn** [LittlePey/SFD#6]
Hi,@LittlePey.
I really love your work, the code and the paper.
But I got a question like the title said.
How to evaluate the model in different distence and different occlusion degrees with KITTI like table 8 in your paper?
I have read you paper and code carefully,But I didn't see those codes about distence and occlusion.
Sorry to propose this silly question.I have a bad coding level. :(
Could you give me some advices or something else?
Thank you!

**Comment by LittlePey** [comment]
Hi, you can re-define the difficulty when [generating infos](https://github.com/LittlePey/SFD/blob/1a46d54d3564ccec0419e95e9781ab1a3deef227/pcdet/datasets/kitti/kitti_dataset_sfd.py#L166).

**Comment by Zyq1216** [comment]
Have you resolved it yet？May I ask how you did it？

**Comment by Zyq1216** [comment]
Have you resolved it yet？May I ask how you did it？@Raiden-cn

**Comment by Feidashen1** [comment]
> Have you resolved it yet？May I ask how you did it？@Raiden-cn

Hello, have you resolved it yet？ How do we evaluate the model in different distance ?  I have known how to evaluate different occlusion degrees. Maybe we can discuss about it.

**Comment by Raiden-cn** [comment]
I'm sorry, I don't remember the details clearly. I modified the range of GT and prediction box in mAP evaluation to achieve the effect I wanted. @Zyq1216 @Feidashen1

**Comment by Zyq1216** [comment]
I haven't solved it yet.@Feidashen1

**Comment by Feidashen1** [comment]
> I'm sorry, I don't remember the details clearly. I modified the range of GT and prediction box in mAP evaluation to achieve the effect I wanted. @Zyq1216 @Feidashen1
Thank you for your reply. It has been very helpful to me！

**Comment by Karkers** [comment]
I'd like to know exactly what to do to get the same kind of assessment as in the paper, by different distances
