### ISSUE TITLE
Synchronized Augmentation question

### ISSUE THREAD

**Issue by AndyYuan96** [LittlePey/SFD#7]
Hi，thanks for sharing the code，I have some question about the aug, considering that you use pseudo lidar point cloud and raw
lidar point cloud to fuse, so it's naturally that you can use all only lidar 3d detection method's augmentation method, why use long paragraph to say that thing。what's more, do you have experiment about comparing only use pseudo lidar point cloud to detection  with sfd.

**Comment by LittlePey** [comment]
Hi, we use several paragraphs to help readers understand its mechanism and introduce our CPConv. The performance of SFD will drop dramatically with only pseudo point clouds. The role of pseudo clouds should be assisting raw clouds, not replacing raw clouds.
