### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by CBY-9527** [LittlePey/SFD#8]
The inference speed mentioned in the paper is 10.2 fps. In the codes,  the depth complement files have been provided. So how do we get the real inference speed.

**Comment by LittlePey** [comment]
The latency reported in the paper includes the depth completion network, you can refer to the [PENet](http://www.cvlibs.net/datasets/kitti/eval_depth_detail.php?benchmark=depth_completion&result=e6ff2dc223b6c53d69cb75fa8fc058a1435822ab) and [TWISE](http://www.cvlibs.net/datasets/kitti/eval_depth_detail.php?benchmark=depth_completion&result=2ac2536c8df3109c079718620d4cc0bd5a3c0156) for latency of depth completion network.

**Comment by CBY-9527** [comment]
> The latency reported in the paper includes the depth completion network, you can refer to the [PENet](http://www.cvlibs.net/datasets/kitti/eval_depth_detail.php?benchmark=depth_completion&result=e6ff2dc223b6c53d69cb75fa8fc058a1435822ab) and [TWISE](http://www.cvlibs.net/datasets/kitti/eval_depth_detail.php?benchmark=depth_completion&result=2ac2536c8df3109c079718620d4cc0bd5a3c0156) for latency of depth completion network.



Thank you for your reply.
Does the average processing time per frame of depth estimation network + average time per frame of detection network detection represent the final inference time.

**Comment by LittlePey** [comment]
Yes
